create table product(
    id bigint generated by default as identity primary key,
    pname varchar(50),
    count int,
    barcode int,
    purchasePrice double precision,
    salePrice double precision,
    dateOfBirth date
);
